version: '2.4'
services:
  bd:
    image: mysql
    container_name: mysql-crud
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - ciro:/var/lib/mysql

volumes:
  ciro: